export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE';

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const GET_ALL_POST_FAILURE = 'GET_ALL_POST_FAILURE';

export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST';
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS';
export const GET_USER_POST_FAILURE = 'GET_USER_POST_FAILURE';

export const USER_LIKE_POST_REQUEST = 'USER_LIKE_POST_REQUEST';
export const USER_LIKE_POST_SUCCESS = 'USER_LIKE_POST_SUCCESS';
export const USER_LIKE_POST_FAILURE = 'USER_LIKE_POST_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const FIND_POST_BY_ID_REQUEST = 'FIND_POST_BY_ID_REQUEST';
export const FIND_POST_BY_ID_SUCCESS = 'FIND_POST_BY_ID_SUCCESS';
export const FIND_POST_BY_ID_FAILURE = 'FIND_POST_BY_ID_FAILURE';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
